language: java
before_install:
- sudo apt-get update
- chmod +x src/test/resources/drivers/chromedriver

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
deploy:
  provider: heroku
  api_key: 
    secure: $HEROKU
  app: esalud
