language: java
before_install:
- sudo apt-get update
- chmod +x src/test/resources/drivers/geckodriver
    
addons:
  firefox: "latest"

deploy:
  provider: heroku
  api_key: 
    secure: $HEROKU
  app: esalud
