language: java
before_install:
- sudo apt-get update
- sudo apt-get upgrade
- chmod +x src/test/resources/drivers/geckodriver
    
deploy:
  provider: heroku
  api_key: 
    secure: $HEROKU
  app: esalud
